apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-state
spec:
  replicas: 1
  serviceName: db          # required
  selector:
    matchLabels:
      app: dailyneeds-db
  template:
    metadata:
      labels:
        app: dailyneeds-db
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: db-password
          volumeMounts:
            - name: mysql-data-new
              mountPath: /var/lib/mysql
              subPath: mysql
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
  volumeClaimTemplates:
    - metadata:
        name: mysql-data-new
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
