version: '3.8'

services:
  web:
    image: brkdockerhub/phpapplication:phpimage
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - dailyneeds-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dailyneeds
      MYSQL_USER: dailyneeds_user
      MYSQL_PASSWORD: dailyneeds_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dailyneeds-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    ports:
      - "8081:80"
    networks:
      - dailyneeds-network

volumes:
  db_data:

networks:
  dailyneeds-network:
    driver: overlay
    attachable: true
